//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sports_Club
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playerlogin
    {
        public string Player_User_Name { get; set; }
        public string Player_Password { get; set; }
        public string Player_Nick_Name { get; set; }
    }
}
