//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sports_Club
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int Player_Id { get; set; }
        public string Player_Name { get; set; }
        public Nullable<int> Player_Age { get; set; }
        public string Player_Sport { get; set; }
        public string Player_Gender { get; set; }
    }
}
