//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sports_Club
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        public int Trainer_Id { get; set; }
        public string Trainer_Name { get; set; }
        public Nullable<int> Trainer_Age { get; set; }
        public string Trainer_Sport { get; set; }
        public string Trainer_Gender { get; set; }
    }
}
